version: '3'
services:
  user-app:
    container_name: user-app
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - WAIT_HOSTS:mysql=3306
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - docker-mysql
  docker-mysql:
    container_name: docker-mysql
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssword1
      - MYSQL_DATABASE=usertaskdb
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

    healthcheck:
      test: "/usr/bin/mysql --user-root --password=password123 --execute \"SHOW DATABASES\""
      interval: 5s
      timeout: 20s
      retries: 5